import { BiomarkerCategory } from '../types/biomarker-types'

export const ALL_METRIC_CATEGORIES = [
  BiomarkerCategory.Aging,
  BiomarkerCategory.Antioxidants,
  BiomarkerCategory.BloodCellCounts,
  BiomarkerCategory.Bone,
  BiomarkerCategory.Cancer,
  BiomarkerCategory.Cardio,
  BiomarkerCategory.Diabetes,
  BiomarkerCategory.Electrolytes,
  BiomarkerCategory.HeavyMetals,
  BiomarkerCategory.Hormones,
  BiomarkerCategory.Inflammation,
  BiomarkerCategory.Iron,
  BiomarkerCategory.Kidney,
  BiomarkerCategory.LipidProfile,
  BiomarkerCategory.Liver,
  BiomarkerCategory.MetabolicMarkers,
  BiomarkerCategory.Nutrients,
  BiomarkerCategory.Other,
  BiomarkerCategory.Thyroid,
  BiomarkerCategory.VitaminsAndMinerals,
]

export const BLOOD_BIOMARKER_CATEGORIES = [
  BiomarkerCategory.Aging,
  BiomarkerCategory.Antioxidants,
  BiomarkerCategory.BloodCellCounts,
  BiomarkerCategory.Bone,
  BiomarkerCategory.Cardio,
  BiomarkerCategory.Cancer,
  BiomarkerCategory.Diabetes,
  BiomarkerCategory.Electrolytes,
  BiomarkerCategory.HeavyMetals,
  BiomarkerCategory.Hormones,
  BiomarkerCategory.Inflammation,
  BiomarkerCategory.Iron,
  BiomarkerCategory.Kidney,
  BiomarkerCategory.LipidProfile,
  BiomarkerCategory.Liver,
  BiomarkerCategory.MetabolicMarkers,
  BiomarkerCategory.Nutrients,
  BiomarkerCategory.Thyroid,
  BiomarkerCategory.VitaminsAndMinerals,
]