import { BiomarkerId } from '~src/types/biomarker-types'

type Level = 'low' | 'med' | 'high'

export const IMPACT_METRICS: {
  biomarkerId: BiomarkerId
  impactFromNutrition: Level
  impactFromExercise: Level
  impactFromGenetics: Level
  impactFromAge: Level
}[] = [
  {
    biomarkerId: BiomarkerId.WBC,
    impactFromNutrition: 'low',
    impactFromExercise: 'low',
    impactFromGenetics: 'med',
    impactFromAge: 'low',
  },
  {
    biomarkerId: BiomarkerId.RBC,
    impactFromNutrition: 'med',
    impactFromExercise: 'med',
    impactFromGenetics: 'high',
    impactFromAge: 'high',
  },
  {
    biomarkerId: BiomarkerId.Hgb,
    impactFromNutrition: 'med',
    impactFromExercise: 'med',
    impactFromGenetics: 'high',
    impactFromAge: 'high',
  },
  {
    biomarkerId: BiomarkerId.Hct,
    impactFromNutrition: 'med',
    impactFromExercise: 'med',
    impactFromGenetics: 'high',
    impactFromAge: 'high',
  },
  {
    biomarkerId: BiomarkerId.PLT,
    impactFromNutrition: 'low',
    impactFromExercise: 'low',
    impactFromGenetics: 'med',
    impactFromAge: 'high',
  },
  {
    biomarkerId: BiomarkerId.Glu,
    impactFromNutrition: 'high',
    impactFromExercise: 'high',
    impactFromGenetics: 'high',
    impactFromAge: 'high',
  },
  {
    biomarkerId: BiomarkerId.BUN,
    impactFromNutrition: 'med',
    impactFromExercise: 'low',
    impactFromGenetics: 'med',
    impactFromAge: 'high',
  },
  {
    biomarkerId: BiomarkerId.Crea,
    impactFromNutrition: 'low',
    impactFromExercise: 'high',
    impactFromGenetics: 'med',
    impactFromAge: 'high',
  },
  {
    biomarkerId: BiomarkerId.UA,
    impactFromNutrition: 'high',
    impactFromExercise: 'med',
    impactFromGenetics: 'high',
    impactFromAge: 'high',
  },
  {
    biomarkerId: BiomarkerId.CHOL,
    impactFromNutrition: 'high',
    impactFromExercise: 'high',
    impactFromGenetics: 'high',
    impactFromAge: 'high',
  },
  {
    biomarkerId: BiomarkerId.LDL,
    impactFromNutrition: 'high',
    impactFromExercise: 'high',
    impactFromGenetics: 'high',
    impactFromAge: 'high',
  },
  {
    biomarkerId: BiomarkerId.HDL,
    impactFromNutrition: 'high',
    impactFromExercise: 'high',
    impactFromGenetics: 'high',
    impactFromAge: 'high',
  },
  {
    biomarkerId: BiomarkerId.Tg,
    impactFromNutrition: 'high',
    impactFromExercise: 'high',
    impactFromGenetics: 'med',
    impactFromAge: 'high',
  },
  {
    biomarkerId: BiomarkerId.Alb,
    impactFromNutrition: 'med',
    impactFromExercise: 'low',
    impactFromGenetics: 'low',
    impactFromAge: 'low',
  },
  {
    biomarkerId: BiomarkerId.ALT,
    impactFromNutrition: 'med',
    impactFromExercise: 'med',
    impactFromGenetics: 'low',
    impactFromAge: 'low',
  },
  {
    biomarkerId: BiomarkerId.AST,
    impactFromNutrition: 'med',
    impactFromExercise: 'high',
    impactFromGenetics: 'low',
    impactFromAge: 'low',
  },
  {
    biomarkerId: BiomarkerId.Bil,
    impactFromNutrition: 'low',
    impactFromExercise: 'low',
    impactFromGenetics: 'med',
    impactFromAge: 'low',
  },
  {
    biomarkerId: BiomarkerId.B12,
    impactFromNutrition: 'high',
    impactFromExercise: 'low',
    impactFromGenetics: 'med',
    impactFromAge: 'med',
  },
  {
    biomarkerId: BiomarkerId.Ca,
    impactFromNutrition: 'high',
    impactFromExercise: 'low',
    impactFromGenetics: 'med',
    impactFromAge: 'high',
  },
  {
    biomarkerId: BiomarkerId.CRP,
    impactFromNutrition: 'med',
    impactFromExercise: 'med',
    impactFromGenetics: 'low',
    impactFromAge: 'low',
  },
  {
    biomarkerId: BiomarkerId.D,
    impactFromNutrition: 'high',
    impactFromExercise: 'low',
    impactFromGenetics: 'med',
    impactFromAge: 'high',
  },
  {
    biomarkerId: BiomarkerId.eGFR,
    impactFromNutrition: 'low',
    impactFromExercise: 'med',
    impactFromGenetics: 'high',
    impactFromAge: 'high',
  },
  {
    biomarkerId: BiomarkerId.Fe,
    impactFromNutrition: 'high',
    impactFromExercise: 'low',
    impactFromGenetics: 'med',
    impactFromAge: 'med',
  },
  {
    biomarkerId: BiomarkerId.Fer,
    impactFromNutrition: 'high',
    impactFromExercise: 'low',
    impactFromGenetics: 'med',
    impactFromAge: 'med',
  },
  {
    biomarkerId: BiomarkerId.FOL,
    impactFromNutrition: 'high',
    impactFromExercise: 'low',
    impactFromGenetics: 'med',
    impactFromAge: 'low',
  },
  {
    biomarkerId: BiomarkerId.HbA1c,
    impactFromNutrition: 'high',
    impactFromExercise: 'high',
    impactFromGenetics: 'high',
    impactFromAge: 'high',
  },
  {
    biomarkerId: BiomarkerId.hsCRP,
    impactFromNutrition: 'med',
    impactFromExercise: 'med',
    impactFromGenetics: 'low',
    impactFromAge: 'low',
  },
  {
    biomarkerId: BiomarkerId.Ins,
    impactFromNutrition: 'high',
    impactFromExercise: 'high',
    impactFromGenetics: 'high',
    impactFromAge: 'high',
  },
  {
    biomarkerId: BiomarkerId.Mg,
    impactFromNutrition: 'high',
    impactFromExercise: 'low',
    impactFromGenetics: 'low',
    impactFromAge: 'med',
  },
  {
    biomarkerId: BiomarkerId.Na,
    impactFromNutrition: 'high',
    impactFromExercise: 'low',
    impactFromGenetics: 'low',
    impactFromAge: 'low',
  },
  {
    biomarkerId: BiomarkerId.K,
    impactFromNutrition: 'high',
    impactFromExercise: 'low',
    impactFromGenetics: 'low',
    impactFromAge: 'low',
  },
  {
    biomarkerId: BiomarkerId.Cl,
    impactFromNutrition: 'high',
    impactFromExercise: 'low',
    impactFromGenetics: 'low',
    impactFromAge: 'low',
  },
  {
    biomarkerId: BiomarkerId.TSH,
    impactFromNutrition: 'med',
    impactFromExercise: 'low',
    impactFromGenetics: 'high',
    impactFromAge: 'med',
  },
  {
    biomarkerId: BiomarkerId.T,
    impactFromNutrition: 'low',
    impactFromExercise: 'med',
    impactFromGenetics: 'high',
    impactFromAge: 'high',
  },
  {
    biomarkerId: BiomarkerId.FT,
    impactFromNutrition: 'low',
    impactFromExercise: 'med',
    impactFromGenetics: 'high',
    impactFromAge: 'high',
  },
  {
    biomarkerId: BiomarkerId.TIBC,
    impactFromNutrition: 'high',
    impactFromExercise: 'low',
    impactFromGenetics: 'med',
    impactFromAge: 'med',
  },
  {
    biomarkerId: BiomarkerId.TS,
    impactFromNutrition: 'high',
    impactFromExercise: 'low',
    impactFromGenetics: 'med',
    impactFromAge: 'med',
  },
  {
    biomarkerId: BiomarkerId.TP,
    impactFromNutrition: 'med',
    impactFromExercise: 'low',
    impactFromGenetics: 'low',
    impactFromAge: 'low',
  },
  {
    biomarkerId: BiomarkerId.VLDL,
    impactFromNutrition: 'high',
    impactFromExercise: 'high',
    impactFromGenetics: 'med',
    impactFromAge: 'high',
  },
  {
    biomarkerId: BiomarkerId.ApoB,
    impactFromNutrition: 'high',
    impactFromExercise: 'high',
    impactFromGenetics: 'high',
    impactFromAge: 'high',
  },
  {
    biomarkerId: BiomarkerId.Cor,
    impactFromNutrition: 'low',
    impactFromExercise: 'med',
    impactFromGenetics: 'med',
    impactFromAge: 'low',
  },
  {
    biomarkerId: BiomarkerId.CK,
    impactFromNutrition: 'low',
    impactFromExercise: 'high',
    impactFromGenetics: 'med',
    impactFromAge: 'med',
  },
  {
    biomarkerId: BiomarkerId.HRV,
    impactFromNutrition: 'low',
    impactFromExercise: 'high',
    impactFromGenetics: 'med',
    impactFromAge: 'high',
  },
  {
    biomarkerId: BiomarkerId.VO2Max,
    impactFromNutrition: 'low',
    impactFromExercise: 'high',
    impactFromGenetics: 'high',
    impactFromAge: 'high',
  },
  {
    biomarkerId: BiomarkerId.HORVATH,
    impactFromNutrition: 'med',
    impactFromExercise: 'med',
    impactFromGenetics: 'high',
    impactFromAge: 'high',
  },
  {
    biomarkerId: BiomarkerId.DunedinPACE,
    impactFromNutrition: 'med',
    impactFromExercise: 'high',
    impactFromGenetics: 'high',
    impactFromAge: 'high',
  },
]
